[project]
name = "investopedia-leaderboard"
version = "0.1.0"
description = "Add a short description here"
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
python = ">=3.13.0,<3.14"
requests = ">=2.32.3,<2.33"
beautifulsoup4 = ">=4.12.3,<4.13"
selenium = ">=4.25.0,<4.26"
webdriver-manager = ">=4.0.2,<4.1"
