name: Make Leaderboard Page
run-name: Leaderboard Update
on: [push]
jobs:
  Make-Leaderboard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ls -la && echo $PWD
      - uses: prefix-dev/setup-pixi@v0.8.0
        with:
          pixi-version: v0.34.0
          cache: true
      - run: pixi run all